[network]
name = "simnet"

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
balance = 100000000000000

[accounts.wallet_1]  
mnemonic = "sell invite acquire kitten bamboo drastic junk such code pasta thunder capable"
balance = 100000000000000

[accounts.wallet_2]
mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey"
balance = 100000000000000